[workspace]
resolver = "2"

members = ["integration-tests", "madara-prover-common", "madara-prover-rpc-client", "madara-prover-rpc-server", "stone-prover", "test-cases", "test-fixtures"]

[workspace.dependencies]
cairo-vm = { git = "https://github.com/Moonsong-Labs/cairo-vm", branch = "od/bootloader-hint-prepare-simple-bootloader-output-segment", features = ["lambdaworks-felt"] }
prost = "0.12.1"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
tempfile = "3.8.1"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["macros", "process", "rt-multi-thread"] }
tonic = "0.10.2"
tonic-build = "0.10.2"
rstest = "0.18.2"

[patch."https://github.com/Moonsong-Labs/cairo-vm"]
cairo-vm = { path = "../starkware/cairo-vm/vm" }
