[workspace]
resolver = "2"

members = ["madara-prover-rpc-client", "madara-prover-rpc-server", "stone-prover", "test-cases"]

[workspace.dependencies]
cairo-vm = { version = "0.9.0", features = ["lambdaworks-felt"] }
prost = "0.12.1"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["macros", "process", "rt-multi-thread"] }
tonic = "0.10.2"
tonic-build = "0.10.2"
rstest = "0.18.2"
