[package]
name = "madara-prover-rpc-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-vm = { version = "0.9.0", features = ["lambdaworks-felt"] }
prost = { workspace = true }
stone-prover = { path = "../stone-prover" }
thiserror = {workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
serde_json = { workspace = true }
tokio-stream = "0.1.14"
bincode = "2.0.0-rc.3"

[build-dependencies]
tonic-build = { workspace = true }

[dev-dependencies]
test-toolkit = { path = "../test-toolkit" }

